### ISSUE TITLE
Program při běhu vyhodí chybu

### ISSUE THREAD

**Issue by xtompok** [matyasm1995/uvod_do_prg#11]
```
set projectionM
set the radius of the Earth in km or enter 0 to set radius to 6371.11km1
set the scale50
meridians: ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-' '-']
parallels: ['-', '-', '-', '-', '-', '-', '-', '-', '-', 0.0, '-', '-', '-', '-', '-', '-', '-'
enter latitude of point100
enter latitude of point again90
enter longitude of point100
x = -
y = -
enter latitude of point
Not a number
enter latitude of point0
enter longitude of point0
x = 0.0
y = 0.0
Traceback (most recent call last):
  File "vypocet_souradnic.py", line 267, in <module>
    graphic(i, j) #grafika
  File "vypocet_souradnic.py", line 212, in graphic
    xi = x / ((i - 1) / 2)
UnboundLocalError: local variable 'x' referenced before assignment

```

**Comment by matyasm1995** [comment]
ošetřeno
