### ISSUE TITLE
Program spadne při zadávání souřadnic bodu

### ISSUE THREAD

**Issue by xtompok** [matyasm1995/uvod_do_prg#23]
```set projection M
set the radius of the Earth in km or enter 0 to set radius to 6371.11km 0
set the scale 50000000
meridians: [-40.0, -37.8, -35.6, -33.4, -31.1, -28.9, -26.7, -24.5, -22.2, -20.0, -17.8, -15.6, -13.3, -11.1, -8.9, -6.7, -4.4, -2.2, 0.0, 2.2, 4.4, 6.7, 8.9, 11.1, 13.3, 15.6, 17.8, 20.0, 22.2, 24.5, 26.7, 28.9, 31.1, 33.4, 35.6, 37.8, 40.0]
parallels: ['-', -31.0, -22.1, -16.8, -12.9, -9.7, -7.0, -4.5, -2.2, 0.0, 2.2, 4.5, 7.0, 9.7, 12.9, 16.8, 22.1, 31.0, '-']
enter longitude of point90
enter latitude of point90
x = 20.0
Traceback (most recent call last):
  File "vypocet_souradnic.py", line 283, in <module>
    point_calc(mercator_x, mercator_y)
  File "vypocet_souradnic.py", line 181, in point_calc
    if -100 < projection_y(point[1]) < 100: #osetreni prilis velkeho y
  File "vypocet_souradnic.py", line 88, in mercator_y
    y = R * log((1 / tan(((radians(90 - i)) / 2))))
ZeroDivisionError: float division by zero
```

**Comment by matyasm1995** [comment]
Vyřešeno
